development:
    twitter:
        consumer_key: 
        consumer_secret: 
    facebook:
        app_id: 
        app_secret: 
    ssl_ca_path: ""
    bitly:
      api_version: 3
      username: jokels
      api_key: 
        
production:
    twitter:
        consumer_key: 
        consumer_secret: 
    facebook:
        app_id: 
        app_secret: 
    ssl_ca_path: /etc/ssl/certs
    bitly:
      api_version: 3
      username: jokels
      api_key: 
